swagger: "2.0"
info:
  title: Acceso Historia
  description: Api para acceso a historia clínica dentro del módulo de Salud del proyecto SIBUD
  version: "1.0"
  termsOfService: http://www.udistrital.edu.co/politicas-de-privacidad.pdf
  contact:
    email: baluist@correo.udistrital.edu.co
  license:
    name: BSD-3-Clause
    url: http://opensource.org/licenses/BSD-3-Clause
basePath: /Salud
paths:
  /AccesoHistoria/:
    get:
      tags:
      - AccesoHistoria
      description: consulta todos los registros de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Get All
      parameters:
      - in: query
        name: query
        description: 'Filtro. Por ejemplo, col1: v1, col2: v2 ...'
        type: string
      - in: query
        name: fields
        description: Campos devueltos. Por ejemplo, col1, col2 ...
        type: string
      - in: query
        name: sortby
        description: Campos ordenados por. Por ejemplo, Col1, col2 ...
        type: string
      - in: query
        name: order
        description: El orden correspondiente a cada campo de clasificación, si es un valor único, se aplica a todos los campos de clasificación. Por ejemplo, desc, asc ...
        type: string
      - in: query
        name: limit
        description: Limite el tamaño del conjunto de resultados. Debe ser un número entero
        type: string
      - in: query
        name: offset
        description: Posición inicial del conjunto de resultados. Debe ser un número entero
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: ""
    post:
      tags:
      - AccesoHistoria
      description: agregar un registro en la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Post
      parameters:
      - in: body
        name: body
        description: Cuerpo para el contenido de AccesoHistoriaClinica
        required: true
        schema:
          $ref: '#/definitions/models.AccesoHistoriaClinica'
      responses:
        "201":
          description: '{int} models.AccesoHistoriaClinica'
        "403":
          description: Cuerpo Vacío
  /AccesoHistoria/{id}:
    get:
      tags:
      - AccesoHistoria
      description: consultar un registro de la tabla AccesoHistoriaClinica por su id
      operationId: AccesoHistoriaClinicaController.Get One
      parameters:
      - in: path
        name: id
        description: Id a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: :id está vacío
    put:
      tags:
      - AccesoHistoria
      description: actualizar un registro de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Put
      parameters:
      - in: path
        name: id
        description: Id del registro a actualizar
        required: true
        type: string
      - in: body
        name: body
        description: Cuerpo para el contenido de AccesoHistoriaClinica
        required: true
        schema:
          $ref: '#/definitions/models.AccesoHistoriaClinica'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: :id no es entero
    delete:
      tags:
      - AccesoHistoria
      description: elimina un registro de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Delete
      parameters:
      - in: path
        name: id
        description: Id del registro a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} borrado exitoso!'
        "403":
          description: Id vacío
definitions:
  models.AccesoHistoriaClinica:
    title: AccesoHistoriaClinica
    type: object
    properties:
      FechaAcceso:
        type: string
        format: datetime
      IdAccesoHistoria:
        type: integer
        format: int64
      IdHistoriaClinica:
        type: integer
        format: int64
      ProfesionaId:
        type: integer
        format: int64
